### ISSUE TITLE
 Deny submissions that don't declare a privileged permission

### ISSUE THREAD

**Issue by wagnerand** [mozilla-extensions/xpi-manifest#136]
⚠️ This is pending on https://bugzilla.mozilla.org/show_bug.cgi?id=1739114, analog to https://github.com/mozilla/addons-server/issues/18254.

During creation of a release or building, when no privileged permission (list TBD) is declared, the task should fail with an error message saying:

_This submission does not declare a privileged permission. It does not need to be signed with the privileged certificate. Please upload it directly to addons.mozilla.org._

**Comment by mixedpuppy** [comment]
Signing should verify at least one of the following permissions are in the permissions key of the manifest.

[
  "activityLog",
  "geckoViewAddons",
  "mozillaAddons",
  "nativeMessagingFromContent",
  "networkStatus",
  "normandyAddonStudy",
  "privilegedAddon",
  "telemetry",
  "urlbar",
]

**Comment by mixedpuppy** [comment]
I would prefer requiring "privilegedAddon" to gain a privileged signing.  That way addition or removal of future privileged permissions would not break signing.  

The privilegedAddon permission is in bug https://bugzilla.mozilla.org/show_bug.cgi?id=1739114

**Comment by willdurand** [comment]
> As a first step, the addons-linter is enabled in [xpi-template](https://github.com/mozilla-extensions/xpi-template) (thanks to [mozilla-extensions/xpi-template#31](https://github.com/mozilla-extensions/xpi-template/pull/31)).

I filed https://github.com/mozilla-extensions/xpi-template/issues/33 to enable the privileged feature (first that will be a no-op but once we land actual changes in the linter, nothing will break and devs will be notified in their repos). That won't affect shipit AFAIK because xpi-manifest does not execute the linter (yet).

**Comment by willdurand** [comment]
See also: https://mozilla-hub.atlassian.net/browse/RELENG-575

**Comment by willdurand** [comment]
This is probably fixed now that #170 (and related PRs) landed.
