### ISSUE TITLE
addon+version uniqueness won't be compatible with MV3 (new version format)

### ISSUE THREAD

**Issue by willdurand** [mozilla-extensions/xpi-manifest#185]
The addon+version uniqueness implemented in https://github.com/mozilla-extensions/xpi-manifest/pull/135 will not be compatible with MV3 because we encourage a new simpler version string format in the manifest. In practice, it means:

- letters are no longer allowed
- the string should have between 1 and 4 numbers separated with dots
- each number should have up to 9 digits
- for non-zero numbers, leading zeros are not allowed

We'll need to update the `build` step to account for that when MV3 extensions will start to be signed. At the moment, MV3 extensions won't be accepted by the linter, though (the linter task is blocking for privileged add-ons since #169).

**Comment by willdurand** [comment]
This bug is semi-related to this issue, although the XPI is an MV2 extension: https://bugzilla.mozilla.org/show_bug.cgi?id=1795750

**Comment by escapewindow** [comment]
We'll need to update [this code](https://github.com/mozilla-extensions/xpi-manifest/blob/c6a142a33b44200edc15f779743b1b895d584fe7/taskcluster/docker/node/build.py#L75-L89) when we decide what the version should look like.

**Comment by escapewindow** [comment]
We could do `major.minor.dot.YYmmddHHM`, which would allow a unique build every 10 minutes. Or specify that addons pipeline web extensions can only specify `major.minor`, and do `major.minor.YYmmdd.HHMMSS` to keep the current unique-to-the-second versioning.

**Comment by gabrielBusta** [comment]
It seems there's a warning about this in Firefox now https://github.com/mozilla-extensions/aboutsync/issues/110

**Comment by gabrielBusta** [comment]
I'm thinking of going with `major.minor.YYmmdd.HHMMSS`

**Comment by willdurand** [comment]
> I'm thinking of going with `major.minor.YYmmdd.HHMMSS`

We probably need to document the fact that extensions will only be able to use `major.minor` in their manifest. Ideally this limitation would be enforced in CI (in the https://github.com/mozilla-extensions/xpi-template repo?) so that everyone knows about the limitation.

**Comment by willdurand** [comment]
One more thing: `HH` might produce leading zeros, which are not accepted by the new version format.

**Comment by jcristau** [comment]
Can you please reconsider this new format?

**Comment by willdurand** [comment]
Sorry, I don't think that's an option.

**Comment by willdurand** [comment]
FYI, I landed a patch to update the version string in langpacks: https://bugzilla.mozilla.org/show_bug.cgi?id=1796531

**Comment by willdurand** [comment]
@gabrielBusta hey, any progress on this? (I am just curious, this is the last identified bug I have for the rollout of this new version format) Thanks!

**Comment by gabrielBusta** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1824240

**Comment by willdurand** [comment]
Yay, thank you!
