### ISSUE TITLE
potentially add AMO verification tests as blocking release build tests

### ISSUE THREAD

**Issue by escapewindow** [mozilla-extensions/xpi-manifest#46]
When trying to submit pioneer-v2-example to AMO, we hit a square icon test failure.

Ideally we should find out about that sooner. Release build tests would be good. CI tests would be even better, so we know ahead of time.

We probably need to figure out which addons will be AMO bound, so we only run the tests on those addons.

**Comment by escapewindow** [comment]
rhelmer  3 minutes ago
yeah that's a really good idea. even if it's not bound for AMO, having the validator run would be valuable imho.
aki  2 minutes ago
build graph is here https://firefox-ci-tc.services.mozilla.com/tasks/groups/cD0NJVyWQFmAtzZ3fuj20Q
theone  < 1 minute ago
yes, you'd probably want to run web-ext lint against the file
aki  < 1 minute ago
oh, that's easy to add to package.json

**Comment by wagnerand** [comment]
I can see two options here:
* Maintainers of the privileged add-on add `web-ext lint` to their test/build action chain. This would have to be done for every existing and new add-on.
* `web-ext lint` is added to the taskcluster standard build definition for privileged add-ons. This would have to be done once be releng.

@escapewindow @rhelmer thoughts?

**Comment by willdurand** [comment]
I think this has been implemented in https://github.com/mozilla-extensions/xpi-template/pull/31 (without `web-ext`)
