### ISSUE TITLE
Signing needs clarification

### ISSUE THREAD

**Issue by mixedpuppy** [mozilla-extensions/xpi-manifest#7]
The docs refer to release signing.  What does that mean?

Also, the "Configuring email notifications" section only refers to privileged and system addons.  Assuming the system addon population will always be minimal, I'll address privileged.  We do not want all addons to be privileged unless they must be so.  What are the controls and constraints here?  How does one configure a non-privileged signing for the addon?

**Comment by escapewindow** [comment]
This automation is currently *only* for privileged webextensions and system addons. Release signing is signing that is valid for shipping to end users on Firefox nightly, beta, release, and esr.

**Comment by mixedpuppy** [comment]
> This automation is currently only for privileged webextensions and system addons.

Why?

**Comment by escapewindow** [comment]
The ask was to provide automation for privileged webextensions and system addon signing, particularly for Normandy. This is finally finished in H2 of 2019. We haven't switched anything over completely to it yet. I imagine we could extend it for other types of xpis, but that hasn't come up until this issue.

**Comment by escapewindow** [comment]
[This doc](https://docs.google.com/document/d/1OhOg1hqw8V-8M7xae3UnZK3pIEMQxJPTZundDxCe-v8/edit?pli=1) has the project proposal.

**Comment by mixedpuppy** [comment]
Having some of that basic information at the top level of the project readme would give context and reduce the questions.
